import { useEffect, useState } from 'react';
import { checkPreset, checkWorkflow, getPreset, getSettings, saveSettings, testCodex, testComfy } from './codex';
import type { Settings } from './codex';
import WorkflowGraph from './WorkflowGraph';
import JsonSyntaxEditor from './JsonSyntaxEditor';

type WorkflowKind = 'image' | 'imageEdit' | 'video';
function inferWorkflowMappings(kind: WorkflowKind, workflowJson: string) {
  const graph = JSON.parse(workflowJson) as Record<string, { class_type?: string; inputs?: Record<string, unknown> }>;
  const nodes = Object.entries(graph);
  const prompt = nodes.find(([, node]) => node.class_type === 'TextEncodeQwenImage21' && node.inputs && Object.hasOwn(node.inputs, 'prompt'))
    || nodes.find(([, node]) => node.class_type?.includes('Text') && node.inputs && Object.hasOwn(node.inputs, 'text'));
  const reference = nodes.find(([, node]) => node.class_type === 'LoadImage' && node.inputs && Object.hasOwn(node.inputs, 'image'));
  const sampler = nodes.find(([, node]) => node.class_type === 'KSampler' && node.inputs && Object.hasOwn(node.inputs, 'seed') && (!prompt || String((node.inputs.positive as unknown[] | undefined)?.[0]) === prompt[0]))
    || nodes.find(([, node]) => node.class_type === 'KSampler' && node.inputs && Object.hasOwn(node.inputs, 'seed'));
  const latent = nodes.find(([, node]) => ['EmptyLatentImage', 'EmptySD3LatentImage'].includes(node.class_type || '') && node.inputs);
  const mappings: Record<string, string> = {};
  if (prompt) { mappings.promptNodeId = prompt[0]; mappings.promptInput = Object.hasOwn(prompt[1].inputs || {}, 'prompt') ? 'prompt' : 'text'; }
  if (reference && kind !== 'video') { mappings.referenceNodeId = reference[0]; mappings.referenceInput = 'image'; }
  if (sampler) {
    mappings.seedNodeId = sampler[0]; mappings.seedInput = 'seed';
    for (const input of ['steps', 'cfg']) if (Object.hasOwn(sampler[1].inputs || {}, input)) { mappings[`${input}NodeId`] = sampler[0]; mappings[`${input}Input`] = input; }
  }
  if (latent) for (const input of ['width', 'height']) {
    if (Number.isFinite(latent[1].inputs?.[input])) { mappings[`${input}NodeId`] = latent[0]; mappings[`${input}Input`] = input; }
    else { mappings[`${input}NodeId`] = ''; mappings[`${input}Input`] = input; }
  }
  return mappings;
}
export default function SettingsPage() {
  const [draft, setDraft] = useState<Settings | null>(null);
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getSettings().then(setDraft).catch(e => setError((e as Error).message)); }, []);
  function codex<K extends keyof Settings['codex']>(key: K, value: Settings['codex'][K]) { setDraft(s => s ? { ...s, codex: { ...s.codex, [key]: value } } : s); }
  function comfyUrl(value: string) { setDraft(s => s ? { ...s, comfy: { ...s.comfy, baseUrl: value } } : s); }
  function workflow(kind: WorkflowKind, key: string, value: string | number) { setDraft(s => s ? { ...s, comfy: { ...s.comfy, [kind]: { ...s.comfy[kind], [key]: value } } } : s); }
  function videoSlots(change: (slots: NonNullable<Settings['comfy']['video']['referenceSlots']>) => NonNullable<Settings['comfy']['video']['referenceSlots']>) { setDraft(s => s ? { ...s, comfy: { ...s.comfy, video: { ...s.comfy.video, referenceSlots: change(s.comfy.video.referenceSlots || []) } } } : s); }
  async function action(name: string, run: () => Promise<string>) { setBusy(name); setError(''); setMessage(''); try { setMessage(await run()); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  if (!draft) return <div className="settings-page"><h1>设置</h1><p className="muted">{error || '正在加载本机设置…'}</p><button className="btn" onClick={() => getSettings().then(setDraft).catch(e => setError((e as Error).message))}>重试</button></div>;
  const field = (kind: WorkflowKind, label: string, id: string, input: string, optional = false) => <div className="settings-fields" key={`${kind}-${id}`}><label>{label}节点 ID{optional ? ' · 可选' : ''}<input value={String(draft.comfy[kind][id as keyof typeof draft.comfy[typeof kind]])} onChange={e => workflow(kind, id, e.target.value)} placeholder="如 6"/></label><label>输入字段<input value={String(draft.comfy[kind][input as keyof typeof draft.comfy[typeof kind]])} onChange={e => workflow(kind, input, e.target.value)}/></label></div>;
  const section = (kind: WorkflowKind) => {
    const config = draft.comfy[kind]; const image = kind !== 'video'; const title = kind === 'image' ? 'Qwen 文生图' : kind === 'imageEdit' ? 'Qwen 参考图编辑' : 'MiniMax H3 首帧图生视频';
    const graphMappings = image ? [
      { id: config.promptNodeId, title: '提示词' }, { id: config.referenceNodeId, title: '参考图' }, { id: config.seedNodeId, title: '随机种子' },
      { id: draft.comfy[kind as 'image' | 'imageEdit'].widthNodeId, title: '宽度' }, { id: draft.comfy[kind as 'image' | 'imageEdit'].heightNodeId, title: '高度' },
      { id: draft.comfy[kind as 'image' | 'imageEdit'].stepsNodeId, title: '采样步数' }, { id: draft.comfy[kind as 'image' | 'imageEdit'].cfgNodeId, title: 'CFG' }
    ] : [{ id: config.promptNodeId, title: '提示词' }, { id: config.referenceNodeId, title: '首帧图' }, { id: config.seedNodeId, title: '随机种子' }, { id: draft.comfy.video.durationNodeId, title: '视频时长' }];
    return <section className="panel settings-panel" key={kind}><div className="section-heading"><h2>本地{title}</h2><span className="eyebrow">{image ? 'IMAGE' : 'VIDEO'} WORKFLOW</span></div><p className="muted">已提供默认 API 节点配置，也可导入自己的 ComfyUI 工作流。{kind === 'video' ? '使用分镜图片作为首帧。' : kind === 'imageEdit' ? '有参考图时使用这个工作流。' : '不选择参考图时使用这个工作流。'}</p>
      <div className="inline-actions"><button className="btn small" disabled={!!busy} onClick={() => action(`preset-${kind}`, async () => { const preset = await getPreset(kind); setDraft(s => s ? { ...s, comfy: { ...s.comfy, [kind]: preset } } : s); return `${title}预设已填入，请保存设置。`; })}>恢复默认节点配置</button><button className="btn small" disabled={!!busy || !config.workflowJson} onClick={() => action(`preset-check-${kind}`, async () => { const result = await checkPreset(draft.comfy.baseUrl, config); return result.ok ? `${title}所需节点和模型已安装。` : `缺少节点：${result.missingNodes.join('、') || '无'}；缺少模型：${result.missingModels.join('、') || '无'}`; })}>检查当前节点与模型</button></div>
      <div className="settings-workflow-head"><h3>ComfyUI 节点图</h3><label className="btn small">导入 API 工作流<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 2_000_000) throw new Error('工作流 JSON 不得超过 2 MB。'); const workflowJson = await file.text(); const mappings = inferWorkflowMappings(kind, workflowJson); setDraft(s => s ? { ...s, comfy: { ...s.comfy, [kind]: { ...s.comfy[kind], workflowJson, ...mappings } } } : s); setMessage(`已导入 ${file.name}，并自动识别提示词、参考图、随机种子、步数和 CFG 节点；请保存设置。`); setError(''); } catch (e) { setError((e as Error).message || '无法读取工作流 JSON。'); } finally { e.target.value = ''; } }}/></label></div>
      <WorkflowGraph workflowJson={config.workflowJson} mappings={graphMappings.filter(item => !!item.id)}/>
      <details className="settings-workflow-json"><summary>高级：查看或编辑 API 工作流 JSON</summary><JsonSyntaxEditor value={config.workflowJson} onChange={value => workflow(kind, 'workflowJson', value)}/></details>
      {field(kind, '提示词', 'promptNodeId', 'promptInput')}{field(kind, image ? '参考图' : '首帧图片', 'referenceNodeId', 'referenceInput', kind === 'image')}{!image && field(kind, '时长', 'durationNodeId', 'durationInput')}{field(kind, '随机种子', 'seedNodeId', 'seedInput', true)}
      {!image && <div className="settings-multi-refs"><div className="section-heading"><h3>分段视频多图切点</h3><button className="btn small" disabled={(draft.comfy.video.referenceSlots?.length || 0) >= 7} onClick={() => videoSlots(slots => [...slots, { imageNodeId: '', imageInput: 'image', timeNodeId: '', timeInput: 'seconds' }])}>＋ 添加图片节点</button></div><p className="hint">第 1 张使用上方首帧节点，之后每张需要图片节点和切点秒数节点。未配置时分段视频仅使用首镜图。</p>{(draft.comfy.video.referenceSlots || []).map((slot, index) => <div className="settings-fields" key={index}><label>图 {index + 2} 节点 ID<input value={slot.imageNodeId} onChange={e => videoSlots(slots => slots.map((item, i) => i === index ? { ...item, imageNodeId: e.target.value } : item))}/></label><label>图片字段<input value={slot.imageInput} onChange={e => videoSlots(slots => slots.map((item, i) => i === index ? { ...item, imageInput: e.target.value } : item))}/></label><label>切点节点 ID<input value={slot.timeNodeId} onChange={e => videoSlots(slots => slots.map((item, i) => i === index ? { ...item, timeNodeId: e.target.value } : item))}/></label><label>切点字段<input value={slot.timeInput} onChange={e => videoSlots(slots => slots.map((item, i) => i === index ? { ...item, timeInput: e.target.value } : item))}/></label><button className="btn small" onClick={() => videoSlots(slots => slots.filter((_, i) => i !== index))}>移除</button></div>)}</div>}
      {image && <>{field(kind, '宽度', 'widthNodeId', 'widthInput', true)}{field(kind, '高度', 'heightNodeId', 'heightInput', true)}{field(kind, '采样步数', 'stepsNodeId', 'stepsInput', true)}{field(kind, 'CFG', 'cfgNodeId', 'cfgInput', true)}</>}
      <button className="btn" disabled={!config.workflowJson || !!busy} onClick={() => action(`check-${kind}`, async () => { const result = await checkWorkflow(config.workflowJson, config.promptNodeId, config.promptInput); return `工作流格式有效，包含 ${result.nodeCount} 个节点；保存设置时会检查全部映射。`; })}>检查工作流</button>
      <h3 className="settings-subtitle">默认参数</h3><div className="settings-fields">{(image ? [['width', '宽度'], ['height', '高度'], ['steps', '采样步数'], ['cfg', 'CFG'], ['seed', '随机种子（-1 为随机）']] : [['duration', '时长（秒，1–15）'], ['seed', '随机种子（-1 为随机）']]).map(([key, label]) => <label key={key}>{label}<input type="number" value={Number(config[key as keyof typeof config])} onChange={e => workflow(kind, key, Number(e.target.value))}/></label>)}</div>
      <p className="hint settings-footnote">预设基于 ComfyUI 官方模板；模型文件需在本机安装，网站不会自动下载。</p>
    </section>;
  };
  return <div className="settings-page"><div className="page-heading"><div><div className="eyebrow">LOCAL SETTINGS</div><h1>设置</h1><p>配置本机 Codex、图片模型与 MiniMax H3 生视频。</p></div><button className="btn primary" disabled={!!busy} onClick={() => action('save', async () => { setDraft(await saveSettings(draft)); return '设置已保存。新任务会使用更新后的参数。'; })}>保存设置</button></div>
    {error && <div className="codex-error">{error}</div>}{message && <div className="settings-success">{message}</div>}
    <section className="panel settings-panel"><h2>主页显示</h2><label className="settings-visibility-toggle"><input type="checkbox" checked={draft.showCreativeTemplates ?? true} onChange={e => setDraft(s => s ? { ...s, showCreativeTemplates: e.target.checked } : s)}/><span><strong>显示创意模板</strong><small>关闭后，主页侧边栏和创建区域都不显示创意模板入口。</small></span></label></section>
    <section className="panel settings-panel"><div className="section-heading"><h2>创作模型</h2><span className="eyebrow">本机服务</span></div><p className="muted">模型和推理强度会应用到新建的创作任务及顾问对话。Ollama 需已在本机启动并安装对应模型。</p><div className="settings-fields"><label>模型服务<select value={draft.codex.provider} onChange={e => codex('provider', e.target.value as Settings['codex']['provider'])}><option value="codex">Codex（默认）</option><option value="ollama">本地 Ollama</option></select></label>{draft.codex.provider === 'codex' ? <label>Codex 模型<input list="codex-model-list" value={draft.codex.model} onChange={e => codex('model', e.target.value)}/><datalist id="codex-model-list"><option value="gpt-5.5"/><option value="gpt-6-sol"/><option value="gpt-6-luna"/></datalist></label> : <label>Ollama 模型<input value={draft.codex.ollamaModel} onChange={e => codex('ollamaModel', e.target.value)} placeholder="gemma4:latest"/></label>}<label>推理强度<select value={draft.codex.reasoningEffort} onChange={e => codex('reasoningEffort', e.target.value as Settings['codex']['reasoningEffort'])}><option value="low">低 · 更快</option><option value="medium">中</option><option value="high">高</option><option value="xhigh">极高</option></select></label><label>单阶段超时（分钟）<input type="number" min="1" max="180" value={draft.codex.timeoutMinutes} onChange={e => codex('timeoutMinutes', Number(e.target.value))}/></label></div>{draft.codex.provider === 'codex' && <><label className="full-label">Codex 可执行文件路径<input value={draft.codex.executablePath || ''} onChange={e => codex('executablePath', e.target.value)} placeholder="例如 C:\path\to\codex.exe"/></label><p className="hint">网页和桌面版都会使用此路径。留空时尝试查找本机已安装的 Codex CLI；填写完整的 codex.exe 路径后，点击“测试当前模型”。</p></>}<button className="btn" disabled={!!busy} onClick={() => action('codex', async () => { const result = await testCodex(draft.codex); return `${draft.codex.provider === 'ollama' ? 'Ollama' : 'Codex'} 模型 ${result.model} 可用 · ${result.reply}`; })}>测试当前模型</button></section>
    <section className="panel settings-panel"><h2>本机 ComfyUI</h2><div className="settings-url-row"><label>服务地址<input value={draft.comfy.baseUrl} onChange={e => comfyUrl(e.target.value)} placeholder="http://127.0.0.1:8188"/></label><button className="btn" disabled={!!busy} onClick={() => action('connection', async () => { const result = await testComfy(draft.comfy.baseUrl); return `连接成功 · ComfyUI ${result.version || '版本未知'}`; })}>测试连接</button></div></section>
    <section className="panel settings-panel"><h2>默认生图方式</h2><div className="settings-fields"><label>生成时默认选择<select value={draft.imageProvider} onChange={e => setDraft(s => s ? { ...s, imageProvider: e.target.value as Settings['imageProvider'] } : s)}><option value="qwen">本机 Qwen-Image-2.1</option><option value="gpt">GPT Image 2.5 · OpenAI API</option></select></label><label>GPT Image 2.5 模型<select value={draft.gptImage.model} onChange={e => setDraft(s => s ? { ...s, gptImage: { ...s.gptImage, model: e.target.value as Settings['gptImage']['model'] } } : s)}><option value="gpt-image-2.5-sunburst">Sunburst · 高质量</option><option value="gpt-image-2.5-flare">Flare · 更快</option></select></label><label>GPT 图片质量<select value={draft.gptImage.quality} onChange={e => setDraft(s => s ? { ...s, gptImage: { ...s.gptImage, quality: e.target.value as Settings['gptImage']['quality'] } } : s)}>{['low','medium','high','xhigh','max'].map(v => <option key={v} value={v}>{v}</option>)}</select></label></div><label className="full-label">OpenAI API Key<input type="password" autoComplete="off" value={draft.gptImage.apiKey || ''} onChange={e => setDraft(s => s ? { ...s, gptImage: { ...s.gptImage, apiKey: e.target.value } } : s)} placeholder={draft.gptImage.hasApiKey ? '已配置；留空保持原值' : '填写 API Key 后保存'}/></label><p className="hint">GPT Image 2.5 使用 OpenAI API，需有可用额度并可能产生费用。API Key 只保存在本机服务，页面不会回显。</p>{draft.gptImage.hasApiKey && <button className="btn small" onClick={() => setDraft(s => s ? { ...s, gptImage: { ...s.gptImage, apiKey: '', hasApiKey: false } } : s)}>保存时清除 API Key</button>}</section>
    {section('image')}{section('imageEdit')}{section('video')}
  </div>;
}
